FROM twilio/twilio-cli

# Use same user as host
ARG UNAME
ARG UID
ARG GID
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME

RUN twilio plugins:install @twilio-labs/plugin-flex